server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/../data/db_phonebook
    username: sa
    password: sa
    #schema: classpath:com/enforceway/db/schema.sql
    #data: classpath:com/enforceway/db/data.sql
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: true
        web-allow-others: true

    #resources:
    #static-locations=file:D:\\espace\\practice\\contacts-manager\\src\\main\\resources\\static
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: input
      update-strategy: not_null
#  config-location: classpath:mybatis/config/mybatis-config.xml
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false